In [1]:
import pandas as pd
import os

In [2]:
path = os.getcwd().replace("\\", "/")

In [3]:
data = pd.read_csv(path + "/heart.csv")

In [4]:
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
5     57    1   0     140   192    0        1       148     0      0.4    1   
6     56    0   1     140   294    0        0       153     0      1.3    1   
7     44    1   1     120   263    0        1       173     0      0.0    2   
8     52    1   2     172   199    1        1       162     0      0.5    2   
9     57    1   2     150   168    0        1       174     0      1.6    2   
10    54    1   0     140   239    0        1       160     0      1.2    2   
11    48    0   2     130   275    0        1       139     0      0.2    2   
12    49    1   1     130   266    0        1       171     0      0.6    2   
13    64    1   3     110   211    0        0       144     1      1.8    1   
14    58    0   3     150   283    1        0       162     0      1.0    2   
15    50    0   2     120   219    0        1       158     0      1.6    1   
16    58    0   2     120   340    0        1       172     0      0.0    2   
17    66    0   3     150   226    0        1       114     0      2.6    0   
18    43    1   0     150   247    0        1       171     0      1.5    2   
19    69    0   3     140   239    0        1       151     0      1.8    2   
20    59    1   0     135   234    0        1       161     0      0.5    1   
21    44    1   2     130   233    0        1       179     1      0.4    2   
22    42    1   0     140   226    0        1       178     0      0.0    2   
23    61    1   2     150   243    1        1       137     1      1.0    1   
24    40    1   3     140   199    0        1       178     1      1.4    2   
25    71    0   1     160   302    0        1       162     0      0.4    2   
26    59    1   2     150   212    1        1       157     0      1.6    2   
27    51    1   2     110   175    0        1       123     0      0.6    2   
28    65    0   2     140   417    1        0       157     0      0.8    2   
29    53    1   2     130   197    1        0       152     0      1.2    0   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
273   58    1   0     100   234    0        1       156     0      0.1    2   
274   47    1   0     110   275    0        0       118     1      1.0    1   
275   52    1   0     125   212    0        1       168     0      1.0    2   
276   58    1   0     146   218    0        1       105     0      2.0    1   
277   57    1   1     124   261    0        1       141     0      0.3    2   
278   58    0   1     136   319    1        0       152     0      0.0    2   
279   61    1   0     138   166    0        0       125     1      3.6    1   
280   42    1   0     136   315    0        1       125     1      1.8    1   
281   52    1   0     128   204    1        1       156     1      1.0    1   
282   59    1   2     126   218    1        1       134     0      2.2    1   
283   40    1   0     152   223    0        1       181     0      0.0    2   
284   61    1   0     140   207    0        0       138     1      1.9    2   
285   46    1   0     140   311    0        1       120     1      1.8    1   
286   59    1   3     134   204    0        1       162     0      0.8    2   
287   57    1   1     154   232    0        0       164     0      0.0    2   
288   57    1   0     110   335    0        1       143     1      3.0    1   
289   55    0   0     128   205    0        2       130     1      2.0    1   
290   61    1   0     148   203    0        1       161     0      0.0    2   
291   58    1   0     114   318    0        2       140

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
std_scl = StandardScaler()

In [7]:
data['age'] = std_scl.fit_transform(data['age'])
data['trtbps'] = std_scl.fit_transform(data['trtbps'])
data['chol'] = std_scl.fit_transform(data['chol'])
data['thalachh'] = std_scl.fit_transform(data['thalachh'])
data['oldpeak'] = std_scl.fit_transform(data['oldpeak'])
data['thall'] = std_scl.fit_transform(data['thall'])

C:\Users\Blot\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
C:\Users\Blot\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
C:\Users\Blot\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
C:\Users\Blot\Anaconda3\lib\site-packages\skl

In [8]:
features = data.iloc[:,0:-1]
target = data.iloc[:,-1]

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size= 0.25)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

In [27]:
knn = KNeighborsClassifier(3)
knn.fit(x_train, y_train)
pred1 = knn.predict(x_test)

In [28]:
svm = SVC(kernel = 'rbf')
svm.fit(x_train, y_train)
pred2 = svm.predict(x_test)

In [29]:
dtree = DecisionTreeClassifier()
dtree.fit(x_train, y_train)
pred3 = dtree.predict(x_test)

In [30]:
nn = MLPClassifier(hidden_layer_sizes = (3), activation = 'relu', solver = 'adam')
nn.fit(x_train, y_train)
pred4 = nn.predict(x_test)

C:\Users\Blot\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


In [15]:
from sklearn.metrics import confusion_matrix,classification_report

In [31]:
print(confusion_matrix(y_test, pred1))
print(confusion_matrix(y_test, pred2))
print(confusion_matrix(y_test, pred3))
print(confusion_matrix(y_test, pred4))
print('KNN:')
print(classification_report(y_test, pred1))
print('SVC:')
print(classification_report(y_test, pred2))
print('DTree:')
print(classification_report(y_test, pred3))
print('Neural Network:')
print(classification_report(y_test, pred4))

[[33 12]
 [ 3 28]]
[[34 11]
 [ 3 28]]
[[40  5]
 [ 8 23]]
[[31 14]
 [ 2 29]]
KNN:
             precision    recall  f1-score   support

          0       0.92      0.73      0.81        45
          1       0.70      0.90      0.79        31

avg / total       0.83      0.80      0.80        76

SVC:
             precision    recall  f1-score   support

          0       0.92      0.76      0.83        45
          1       0.72      0.90      0.80        31

avg / total       0.84      0.82      0.82        76

DTree:
             precision    recall  f1-score   support

          0       0.83      0.89      0.86        45
          1       0.82      0.74      0.78        31

avg / total       0.83      0.83      0.83        76

Neural Network:
             precision    recall  f1-score   support

          0       0.94      0.69      0.79        45
          1       0.67      0.94      0.78        31

avg / total       0.83      0.79      0.79        76

